###################################################################

# Created by write_sdc on Mon Jan 11 23:28:56 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {PC[31]}]
set_load -pin_load 3.40189 [get_ports {PC[30]}]
set_load -pin_load 3.40189 [get_ports {PC[29]}]
set_load -pin_load 3.40189 [get_ports {PC[28]}]
set_load -pin_load 3.40189 [get_ports {PC[27]}]
set_load -pin_load 3.40189 [get_ports {PC[26]}]
set_load -pin_load 3.40189 [get_ports {PC[25]}]
set_load -pin_load 3.40189 [get_ports {PC[24]}]
set_load -pin_load 3.40189 [get_ports {PC[23]}]
set_load -pin_load 3.40189 [get_ports {PC[22]}]
set_load -pin_load 3.40189 [get_ports {PC[21]}]
set_load -pin_load 3.40189 [get_ports {PC[20]}]
set_load -pin_load 3.40189 [get_ports {PC[19]}]
set_load -pin_load 3.40189 [get_ports {PC[18]}]
set_load -pin_load 3.40189 [get_ports {PC[17]}]
set_load -pin_load 3.40189 [get_ports {PC[16]}]
set_load -pin_load 3.40189 [get_ports {PC[15]}]
set_load -pin_load 3.40189 [get_ports {PC[14]}]
set_load -pin_load 3.40189 [get_ports {PC[13]}]
set_load -pin_load 3.40189 [get_ports {PC[12]}]
set_load -pin_load 3.40189 [get_ports {PC[11]}]
set_load -pin_load 3.40189 [get_ports {PC[10]}]
set_load -pin_load 3.40189 [get_ports {PC[9]}]
set_load -pin_load 3.40189 [get_ports {PC[8]}]
set_load -pin_load 3.40189 [get_ports {PC[7]}]
set_load -pin_load 3.40189 [get_ports {PC[6]}]
set_load -pin_load 3.40189 [get_ports {PC[5]}]
set_load -pin_load 3.40189 [get_ports {PC[4]}]
set_load -pin_load 3.40189 [get_ports {PC[3]}]
set_load -pin_load 3.40189 [get_ports {PC[2]}]
set_load -pin_load 3.40189 [get_ports {PC[1]}]
set_load -pin_load 3.40189 [get_ports {PC[0]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[31]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[30]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[29]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[28]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[27]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[26]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[25]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[24]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[23]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[22]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[21]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[20]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[19]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[18]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[17]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[16]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[15]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[14]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[13]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[12]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[11]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[10]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[9]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[8]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[7]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[6]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[5]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[4]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[3]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[2]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[1]}]
set_load -pin_load 3.40189 [get_ports {DM_addr[0]}]
set_load -pin_load 3.40189 [get_ports IM_READ_OUT]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[31]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[30]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[29]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[28]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[27]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[26]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[25]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[24]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[23]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[22]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[21]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[20]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[19]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[18]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[17]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[16]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[15]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[14]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[13]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[12]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[11]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[10]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[9]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[8]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[7]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[6]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[5]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[4]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[3]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[2]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[1]}]
set_load -pin_load 3.40189 [get_ports {WRITE_DATA_OUT[0]}]
set_load -pin_load 3.40189 [get_ports DM_WRITE_OUT]
set_load -pin_load 3.40189 [get_ports DM_READ_OUT]
create_clock [get_ports CLK]  -name MY_CLK  -period 2.5  -waveform {0 1.25}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {INSTR[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DM_data[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {PC[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DM_addr[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports IM_READ_OUT]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {WRITE_DATA_OUT[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports DM_WRITE_OUT]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports DM_READ_OUT]
